%YAML 1.1
# -*- coding: UTF-8, tab-width: 2 -*-
---

version: '2.2'
services:

  ${dd_tpl_bn}'':
    image: 'mongo:5.0'
    restart: 'no'
    volumes:
      - ${dd_dir}'@/mongo.data/v5:/data/db'
    ports:
      - '127.0.0.1:27017:27017'






...
