%YAML 1.1
# -*- coding: UTF-8, tab-width: 4 -*-
---

version: '3'
services:

  mongo:
    image: "mongo:5.0"
    volumes:
      - ${dd_dir}"@/mongo.data/v5:/data/db"
    ports:
      - "127.0.0.1:27017:27017"






...
