%YAML 1.1
# -*- coding: UTF-8, tab-width: 4 -*-
---

version: '3'
services:

  ${dd_tpl_bn}'':
    image: 'adminer:latest'
    restart: always
    environment:
        # For available PHP settings, see https://github.com/wodby/php
        # For available Adminer settings, see https://github.com/wodby/adminer

        #%sed s~\bdf'~'ADMINER_DEFAULT_~
        - df'DB_DRIVER=pgsql'
        - df'SERVER=postgres'
        - df'PORT=5432'
        - df'DB=magic'
        - df'USER=postgres'
        - ${dd_cfg}df'PASSWORD=POSTGRES_PASSWORD'

        - 'ADMINER_DESIGN=pepa-linha-dark'
        - 'ADMINER_PLUGINS='
    ports:
      - '127.0.0.1:5480:8080'


...
