%YAML 1.1
# -*- coding: UTF-8, tab-width: 4 -*-
---

version: '3'
services:

  postgres:
    image: 'postgres:14-alpine'
    volumes:
      - ${dd_dir}'@/postgres.data/v14:/pgdata'
    restart: always
    environment:
      - 'PGDATA=/pgdata'
      # - 'POSTGRES_USER=postgres'
      - ${env_secret}'POSTGRES_PASSWORD='
      # - 'POSTGRES_PASSWORD_FILE=/run/secrets/postgres/initpswd'
    ports:
      - '127.0.0.1:5432:5432'


#  sqlpad:
#    image: 'sqlpad/sqlpad:latest'
#    volumes:
#      - ${dd_dir}'@/sqlpad.data/v-latest:/var/lib/sqlpad'
#    ports:
#      - '127.0.0.1:5430:3000'

  pgadminer:
    image: 'adminer:latest'
    restart: always
    environment:
      - 'ADMINER_DEFAULT_TYPE=postgresql'
      - 'ADMINER_DEFAULT_SERVER=postgres'
      - 'ADMINER_DEFAULT_PORT=5432'
      - 'ADMINER_DEFAULT_DB=magic'
      - 'ADMINER_DEFAULT_USER=postgres'
      - ${env_secret}'ADMINER_DEFAULT_PASSWORD=POSTGRES_PASSWORD'
      - 'ADMINER_DESIGN=pepa-linha-dark'
      - 'ADMINER_PLUGINS='
    ports:
      - '127.0.0.1:5480:8080'


...
