%YAML 1.1
# -*- coding: UTF-8, tab-width: 4 -*-
---

version: '3'
services:

  ${dd_tpl_bn}'':
    image: 'postgres:14-alpine'
    volumes:
      - ${dd_dir}'@/postgres.data/v14:/pgdata'
    restart: always
    environment:
      - 'PGDATA=/pgdata'
      # - 'POSTGRES_USER=postgres'
      - ${dd_cfg}'POSTGRES_PASSWORD='
      # - 'POSTGRES_PASSWORD_FILE=/run/secrets/postgres/initpswd'
    ports:
      - '127.0.0.1:5432:5432'


...
